In [58]:
import sqlite3
import pandas as pd

con=sqlite3.connect('C:\\Users\\minsh\\OneDrive\\Desktop\\OJL_sem_3\\Proj_3.1\\data\\raw\\ipl.db')
def q(sql):
    return pd.read_sql(sql, con)

In [59]:
def run_sql_file(path):
    with open(path,'r') as f:
        script =f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [60]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\test.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\test.sql

In [61]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\01_nulls_and_blanks.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\01_nulls_and_blanks.sql

In [62]:
q("""select count(*) as blank_before
from deliveries
where trim(bowler_type) = '';""")

   blank_before
0             8

In [63]:
q("""select count(*) as null_after
from v_players_clean
where field_pos_clean is null;""")

   null_after
0         700

In [64]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\02_merge_categories.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\02_merge_categories.sql

In [65]:
q("""select distinct team_name
from teams
order by team_name;""")

                      team_name
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13      Rising Pune Supergiants
14  Royal Challengers Bangalore
15          Sunrisers Hyderabad

In [66]:
q("""select distinct team_name_clean
from v_teams_clean;""")

                team_name_clean
0   Royal Challengers Bangalore
1           Sunrisers Hyderabad
2                Mumbai Indians
3        Rising Pune Supergiant
4                 Gujarat Lions
5         Kolkata Knight Riders
6           Chennai Super Kings
7              Rajasthan Royals
8                Delhi Capitals
9                  Punjab Kings
10         Lucknow Super Giants
11               Gujarat Titans
12              Deccan Chargers
13         Kochi Tuskers Kerala
14                Pune Warriors

In [67]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\03_venue_names.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\03_venue_names.sql

In [68]:
q(""" SELECT venue, COUNT(*) AS matches
FROM matches
WHERE venue IN('Wankhede Stadium', 'Wankhede Stadium, Mumbai')
GROUP BY venue;""")

                      venue  matches
0          Wankhede Stadium       73
1  Wankhede Stadium, Mumbai       57

In [69]:
q(""" SELECT venue,COUNT(*) AS matches
FROM matches
GROUP BY venue
ORDER BY matches DESC
LIMIT 10;""")

                                       venue  matches
0                               Eden Gardens       77
1                           Wankhede Stadium       73
2                      M Chinnaswamy Stadium       65
3                           Feroz Shah Kotla       60
4                   Wankhede Stadium, Mumbai       57
5  Rajiv Gandhi International Stadium, Uppal       49
6            MA Chidambaram Stadium, Chepauk       48
7                     Sawai Mansingh Stadium       47
8        Dubai International Cricket Stadium       46
9   MA Chidambaram Stadium, Chepauk, Chennai       38

In [70]:
q(""" select venue_clean, COUNT(*) AS matches
from v_matches_venue
GROUP BY venue_clean
order by matches desc limit 5;""")

                          venue_clean  matches
0                    Wankhede Stadium      130
1               M Chinnaswamy Stadium      104
2                        Eden Gardens      104
3              MA Chidambaram Stadium       95
4  Rajiv Gandhi International Stadium       87

In [71]:
q("""select count(*) as rows,count(distinct venue) as names
from venues;""")

   rows  names
0    63     59

In [72]:
q("""select count(*),venue,city
from venues
group by venue
order by count(*) desc
limit 10;""")

   count(*)                                              venue       city
0         2                            Sharjah Cricket Stadium       None
1         2  Maharaja Yadavindra Singh International Cricke...     Mohali
2         2                Dubai International Cricket Stadium       None
3         2                 Dr DY Patil Sports Academy, Mumbai     Mumbai
4         1                   Zayed Cricket Stadium, Abu Dhabi  Abu Dhabi
5         1                           Wankhede Stadium, Mumbai     Mumbai
6         1                                   Wankhede Stadium     Mumbai
7         1       Vidarbha Cricket Association Stadium, Jamtha     Nagpur
8         1                                    SuperSport Park  Centurion
9         1                         Subrata Roy Sahara Stadium       Pune

In [73]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\04_dedupe_venues.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\04_dedupe_venues.sql

In [74]:
q(""" select count(*) as rows,count(distinct venue) as names
from v_venues_clean;""")

   rows  names
0    59     59

In [75]:
q("""select count(*),venue,city
from v_venues_clean
group by venue
order by count(*) desc
limit 10;""")

   count(*)                                             venue            city
0         1                  Zayed Cricket Stadium, Abu Dhabi       Abu Dhabi
1         1                          Wankhede Stadium, Mumbai          Mumbai
2         1                                  Wankhede Stadium          Mumbai
3         1      Vidarbha Cricket Association Stadium, Jamtha          Nagpur
4         1                                   SuperSport Park       Centurion
5         1                        Subrata Roy Sahara Stadium            Pune
6         1                                  St George's Park  Port Elizabeth
7         1                              Sheikh Zayed Stadium       Abu Dhabi
8         1                           Sharjah Cricket Stadium         Sharjah
9         1  Shaheed Veer Narayan Singh International Stadium          Raipur

In [76]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\05_city_fallback.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\05_city_fallback.sql

In [77]:
q("""select city_clean from v_city_clean
where city_clean = 'UNKNOWN';""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [78]:
q("""select venue,
       count(*) as no_city
from matches
where city is null
group by venue;""")

                                 venue  no_city
0  Dubai International Cricket Stadium       33
1              Sharjah Cricket Stadium       18

In [79]:
q(""" SELECT city_clean FROM v_city_clean
WHERE city_clean IN('UNKNOWN');""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [80]:
q(""" SELECT city_clean FROM v_city_clean
LIMIT 5;""")

  city_clean
0  Bangalore
1  Hyderabad
2       Pune
3     Rajkot
4     Indore

In [81]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\06_season_year.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\06_season_year.sql

In [82]:
q(""" select season,
         count(*) as matches
from matches
where season ='2020/21'
group by season;""")

    season  matches
0  2020/21       60

In [83]:
q(""" select distinct season,
season_year
from v_season
where season='2020/21';""")

    season  season_year
0  2020/21         2020

In [84]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\07_win_definition.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\07_win_definition.sql

In [86]:
run_sql_file(r"C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\08_matches_clean.sql")

ran C:\Users\minsh\OneDrive\Desktop\OJL_sem_3\Proj_3.1\sql\08_matches_clean.sql

In [87]:
q("""select * from matches_clean;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_decision
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,field
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,field
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,field
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,field
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,field
...,...,...,...,...,...,...,...,...
1207,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,field
1208,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,field
1209,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,bat
1210,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,field
1211,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,bat

In [ ]:
import ast
import pandas as pd
d=pd.read_sql('select * from deliveries where fielde')